default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: twitterclone_development
test:
  <<: *default
  database: twitterclone_test
production:
  <<: *default
  database: twitterclone_production
  username: twitterclone
  password: <%= ENV['TWITTERCLONE_DATABASE_PASSWORD'] %>
